on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      meta: ${{ steps.meta.outputs.json }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    env:
      IMAGE: ${{ fromJSON(needs.build-and-push-image.outputs.meta).tags[0] }} # ex. "ghcr.io/thewapp/og-image:main"
    steps:
      - name: Pull docker image
        run: docker pull "$IMAGE"
      - name: Run app
        run: docker run -d -p 8080:8080 "$IMAGE"
      - name:
        run: test $(curl -sw "%{http_code}" localhost:8080 2>/dev/null) = "403"
